#!/usr/bin/with-contenv sh

PUID=${PUID:-99}
PGID=${PGID:-100}

groupmod -o -g "$PGID" xyz
usermod -o -u "$PUID" xyz
chown -R xyz:xyz /opt
chmod -R +x /opt
echo "
-----------------------------------------
              DashBtn
-----------------------------------------
          Brought to you by:             
                                         
 _  _ _     _   _                        
| \| (_)_ _| |_| |_                      
| .' | | ' \  _| ' \                     
|_|\_|_|_||_\__|_||_|                    
__      __    _ _                        
\ \    / /_ _| | |_____ _ _              
 \ \/\/ / _' | | / / -_) '_|             
  \_/\_/\__,_|_|_\_\___|_|               
                                         
-----------------------------------------
User xyz uid set to:  $(id -u xyz)
User xyz gid set to:  $(id -g xyz)
-----------------------------------------
"
